import React from "react";

function Loading(props) {
    const scale = props.scale || '0.6';

    return (
        <svg xmlns="http://www.w3.org/2000/svg" style={{width: '100%', height: '100%', transform: `scale(${scale})`, margin: 'auto', background: 'none', position: 'absolute', display: 'block', shapeRendering: 'auto'}} width="81px" height="81px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <circle cx="50" cy="50" r="32" strokeWidth="8" stroke="#009553" strokeDasharray="50.26548245743669 50.26548245743669" fill="none" strokeLinecap="round">
                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
            </circle>
            { /* generated by https://loading.io/ */ }
        </svg>
    );
}

export default Loading;
